language: generic 
sudo: required #require superuser permission
services:
    - docker
    
before_install:
    - docker build -t jpmc9005/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true jpmc9005/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "eu-west-3"
    app: "docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-eu-west-3-709982155892"
    bucket_path: "docker" #same as app name
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
